runtime: go121  # or another supported version

instance_class: F2

env_variables:
  TOKEN: "test-token"

handlers:
- url: /
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: auto
